import LayoutMyCar from '@/components/layout/LayoutMyCar'
import BackgroundUiProfile from '@/themes/profile/BackgroundUiProfile'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Kanow - Xe của tôi',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <LayoutMyCar>
            <BackgroundUiProfile className='rounded-tl-none'>
                {children}
            </BackgroundUiProfile>
        </LayoutMyCar>
    )
}
