import LayoutProfile from '@/components/layout/LayoutProfile'
import type { Metadata } from 'next'
import { Suspense } from 'react'

export const metadata: Metadata = {
    title: 'Kanow - Thông tin',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Suspense>
            <LayoutProfile>
                {children}
            </LayoutProfile>
        </Suspense>
    )
}
