import type { Metadata } from 'next'
import LayoutContainer from '@/components/layout/LayoutContainer';

export const metadata: Metadata = {
    title: 'Trang chủ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <LayoutContainer>
            {children}
        </LayoutContainer>
    )
}
