import type { Metadata } from 'next'
import LayoutContainer from '@/components/layout/LayoutContainer';
import { GoogleOAuthProvider } from '@react-oauth/google';


export const metadata: Metadata = {
    title: 'Kanow - Trang chủ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <GoogleOAuthProvider clientId={`${process.env.NEXT_PUBLIC_REACT_API_GOOGLE_API_CLIENT_ID}`}>
                <LayoutContainer>
                    {children}
                </LayoutContainer>
            </GoogleOAuthProvider>
        </>
    )
}
