import type { Metadata } from 'next'
import LayoutContainer from '@/components/layout/LayoutContainer';
import { Suspense } from 'react';

export const metadata: Metadata = {
    title: 'Kanow - Trang chủ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <meta name="google-site-verification" content="ig4H1SE4hArs-pmvzmAmlMSVutXaQoJ3yB5UfRUiO_s" />
            </head>
            <LayoutContainer>
                {children}
            </LayoutContainer>
        </html>
    )
}
