import LayoutPolicy from '@/components/layout/LayoutPolicy'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Kanow - Chính sách',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <LayoutPolicy>
            {children}
        </LayoutPolicy>
    )
}
