import LayoutPolicy from '@/components/layout/LayoutPolicy'
import type { Metadata } from 'next'
import { Suspense } from 'react'

export const metadata: Metadata = {
    title: 'Kanow - Chính sách',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <Suspense>
            <LayoutPolicy>
                {children}
            </LayoutPolicy>
        </Suspense>
    )
}
