import LayoutVehicleManagement from '@/components/layout/LayoutVehicleManagement'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Kanow - Quản lý xe',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <LayoutVehicleManagement>
            {children}
        </LayoutVehicleManagement>
    )
}
